### ISSUE TITLE
Silent Typing: Update for new chatbox

### ISSUE THREAD

**Issue by Otaku-2** [noodlebox/betterdiscord-plugins#22]
Just putting this here so it's known that it doesn't work as of right now

**Comment by noodlebox** [comment]
Thanks, the simple part of it is that the class names around the textarea have changed, and just need to be updated to match. The problematic part is that the input event this cancels is now necessary for any text to be sent at all in a message.

Instead of cancelling the event completely like it does now, it will require either:
- monkey patching one of Discord's internal methods on the textarea, or
- replicating some of the default behavior in the input event handler created by this plugin.

Either would solve #8 as well, and be most of the way towards a fix for #17. They both require digging into React internals. Fixing this plugin is a lower priority for me, but I welcome pull requests. Or, if I find a decent solution while fixing #19 (also involving the chatbox), I might be able to fix this one as well.
