### ISSUE TITLE
Silent typing broken?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [noodlebox/betterdiscord-plugins#39]
I assume the objective is to not broadcast the "user is typing" message to everyone else as you're typing. I tested the results with a friend, and it is not accomplishing this objective currently, AFAICT.

**Comment by noodlebox** [comment]
This is most likely due to a race condition that depends on how quickly BD loads, and BD is usually slow enough that it's not an issue. You should be able to work around this for now by disabling and re-enabling the plugin after BD loads. I'll try to update it today along with the other plugins that need fixing.

**Comment by narcolepticinsomniac** [comment]
It's working again AFAICT. Great plugin btw.
