### ISSUE TITLE
Plugins using jQuery no longer work

### ISSUE THREAD

**Issue by OmarUVX** [noodlebox/betterdiscord-plugins#64]
I have a severe issue that all the plugins in that list disable automatically once i enable them and go out of the Settings page/menu, none of them actually work when i enable them though, I will instantly close this issue if they actually worked somehow. All the plugins weren't working, the ones i was using was LineNumbers and OwnerTags only. I hope someone help me with this issue since it lasted for weeks untill now..

**Comment by christiankek** [comment]
Most of the plugins haven’t been updated in 2+ years, they were bound to break eventually.

**Comment by noodlebox** [comment]
Many of them have been obsoleted by stock Discord features (generally a good thing), and some have been better implemented by other plugin authors more active in the community. I haven't used BetterDiscord myself in a long time, so I am not going to be very proactive in maintaining the working condition of the rest.

Often, breakage is simply caused by minor changes in Discord and they're an easy fix. Other times, major changes in BetterDiscord require some more involved fixes. I believe the main issue affecting several plugins recently is the removal of jQuery from BetterDiscord, so the solutions are either the ugly one of bundling jQuery with addons, or the more involved, but cleaner one of replacing jQuery-based code with vanilla JavaScript.

If you're up for either of those, I do accept pull requests!

**Comment by KaKi87** [comment]
> Many of them have been obsoleted by stock Discord features (generally a good thing), and some have been better implemented by other plugin authors more active in the community.

LineNumbers has not.

**Comment by noodlebox** [comment]
> > Many of them have been obsoleted by stock Discord features (generally a good thing), and some have been better implemented by other plugin authors more active in the community.
> 
> LineNumbers has not.

See the second half of the quoted paragraph.

> I haven't used BetterDiscord myself in a long time, so I am not going to be very proactive in maintaining the working condition of the rest.

**Comment by KaKi87** [comment]
How did you stopped needing line numbers with vanilla Discord then ?

**Comment by noodlebox** [comment]
At the moment, I live without the feature.
