### ISSUE TITLE
SilentTyping: Chance to delete comment from picture message

### ISSUE THREAD

**Issue by Otaku-2** [noodlebox/betterdiscord-plugins#8]
With this plugin, there is a chance of when you post a picture with a message attached, it will just send the picture and not the message. I've tested with this plugin off, and it seems to work fine.

**Comment by noodlebox** [comment]
Thanks for reporting, I can reproduce this as well. The contents of the textarea aren't copied over to the upload modal.

Bugs like this are to be expected with this plugin, since it's not careful at all about clobbering other features. It will need a less-trivial implementation for it to cause less "collateral damage", which is why it hasn't been added to the master branch yet.
